# 生产环境配置

# Redis配置
---
redis:
  database: 0 #Redis数据库索引（默认为0）
  host: localhost
  port: 6379
  # 超时，单位毫秒
  timeout: 1000
  password: 766d016efb375eb1e7b663db
  pool:
    max-active: 80 #连接池最大连接数（使用负值表示没有限制）
    max-wait: 2000 #连接最大阻塞等待时间（使用负值表示没有限制）
    max-idle:  20 #连接池中的最大空闲连接
    min-idle: 10 #连接池中的最小空闲连接
    minEvictableIdleTimeMillis: 600000 #10分钟
    timeBetweenEvictionRunsMillis: 180000 # 3分钟
...